Listen 8025
ProxyRequests Off
<VirtualHost *:80>
    ServerName localhost
    ProxyPreserveHost On
    ProxyPass / http://web:80/
    ProxyPassReverse / http://web:80/
</VirtualHost>
<VirtualHost *:8025>
    ServerName localhost
    ProxyPreserveHost On
    ProxyPass / http://mail:8025/
    ProxyPassReverse / http://mail:8025/
</VirtualHost>
